[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= 'nosniff'
    Referrer-Policy= 'no-referrer'
    Strict-Transport-Security= "max-age=31536000; includeSubDomains; preload"

    content-security-policy = '''
    frame-ancestors 'none';
    object-src 'none';
    '''
[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "netlify-plugin-image-optim"

# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
  package = "netlify-plugin-minify-html"

  # Optionally, override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseWhitespace = true
    conservativeCollapse = true
    minifyCSS = true
    minifyJS = true
