[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= 'nosniff'
    Referrer-Policy= 'no-referrer'
    # Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # Cache-Control = "public, max-age=31536000, immutable"
    Strict-Transport-Security= "max-age=31536000; includeSubDomains; preload"

    content-security-policy = '''
    frame-ancestors 'none';
    object-src 'none';
    '''

[[plugins]]
package = "netlify-plugin-debug-cache"
[[plugins]]
package = "netlify-plugin-image-optim"