[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security= "max-age=31536000; includeSubDomains; preload"

    content-security-policy = '''
    frame-ancestors 'none';
    object-src 'none'; 
    '''